<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkmjU67\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkmjU67/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkmjU67.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkmjU67\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJkmjU67\App_KernelDevDebugContainer([
    'container.build_hash' => 'JkmjU67',
    'container.build_id' => '3063687a',
    'container.build_time' => 1608040405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkmjU67');
