<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R5HmrcQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r5HmrcQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r5HmrcQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'uploadService' => ['privates', 'App\\Services\\UploadAvatar', 'getUploadAvatarService', true],
        ], [
            'manager' => '?',
            'uploadService' => 'App\\Services\\UploadAvatar',
        ]);
    }
}
