<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6I08TLgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6I08TLg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6I08TLg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ad' => ['privates', '.errored..service_locator.6I08TLg.App\\Entity\\Ad', NULL, 'Cannot autowire service ".service_locator.6I08TLg": it references class "App\\Entity\\Ad" but no such service exists.'],
            'author' => ['privates', '.errored..service_locator.6I08TLg.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.6I08TLg": it references class "App\\Entity\\User" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'findAdAuthor' => ['privates', 'App\\Services\\FindAdAuthor', 'getFindAdAuthorService', true],
            'sendMail' => ['privates', 'App\\Services\\SenderEmails', 'getSenderEmailsService', true],
        ], [
            'ad' => 'App\\Entity\\Ad',
            'author' => 'App\\Entity\\User',
            'em' => '?',
            'findAdAuthor' => 'App\\Services\\FindAdAuthor',
            'sendMail' => 'App\\Services\\SenderEmails',
        ]);
    }
}
