<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CBNz5E3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CBNz5E3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CBNz5E3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'findAdAuthor' => ['privates', 'App\\Services\\FindAdAuthor', 'getFindAdAuthorService', true],
        ], [
            'em' => '?',
            'findAdAuthor' => 'App\\Services\\FindAdAuthor',
        ]);
    }
}
