<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdMessagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ga6L_7y.App\Entity\AdMessages' shared service.
     *
     * @return \App\Entity\AdMessages
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ga6L_7y": it references class "App\\Entity\\AdMessages" but no such service exists.');
    }
}
