<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CandController' shared autowired service.
     *
     * @return \App\Controller\CandController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CandController.php';

        $container->services['App\\Controller\\CandController'] = $instance = new \App\Controller\CandController(($container->privates['App\\Repository\\CandidatureRepository'] ?? $container->load('getCandidatureRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\CandidatureLightRepository'] ?? $container->load('getCandidatureLightRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\CandController', $container));

        return $instance;
    }
}
