<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VBW94qJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VBW94qJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VBW94qJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidature' => ['privates', '.errored..service_locator.VBW94qJ.App\\Entity\\CandidatureLight', NULL, 'Cannot autowire service ".service_locator.VBW94qJ": it references class "App\\Entity\\CandidatureLight" but no such service exists.'],
        ], [
            'candidature' => 'App\\Entity\\CandidatureLight',
        ]);
    }
}
