<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ga6L7yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ga6L_7y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ga6L_7y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'findAdAuthor' => ['privates', 'App\\Services\\FindAdAuthor', 'getFindAdAuthorService', true],
            'messageDel' => ['privates', '.errored..service_locator.Ga6L_7y.App\\Entity\\AdMessages', NULL, 'Cannot autowire service ".service_locator.Ga6L_7y": it references class "App\\Entity\\AdMessages" but no such service exists.'],
        ], [
            'em' => '?',
            'findAdAuthor' => 'App\\Services\\FindAdAuthor',
            'messageDel' => 'App\\Entity\\AdMessages',
        ]);
    }
}
