<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdImagesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AdImagesType' shared autowired service.
     *
     * @return \App\Form\AdImagesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AdImagesType.php';

        return $container->privates['App\\Form\\AdImagesType'] = new \App\Form\AdImagesType();
    }
}
