<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAd3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OeT5gA..App\Entity\Ad' shared service.
     *
     * @return \App\Entity\Ad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OeT5gA.": it references class "App\\Entity\\Ad" but no such service exists.');
    }
}
