<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatureLightService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VBW94qJ.App\Entity\CandidatureLight' shared service.
     *
     * @return \App\Entity\CandidatureLight
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VBW94qJ": it references class "App\\Entity\\CandidatureLight" but no such service exists.');
    }
}
