<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAdAuthorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\FindAdAuthor' shared autowired service.
     *
     * @return \App\Services\FindAdAuthor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/FindAdAuthor.php';

        return $container->privates['App\\Services\\FindAdAuthor'] = new \App\Services\FindAdAuthor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
