<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifyRegistrationConfirmationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EntityListener\NotifyRegistrationConfirmation' shared autowired service.
     *
     * @return \App\EntityListener\NotifyRegistrationConfirmation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EntityListener/NotifyRegistrationConfirmation.php';

        return $container->privates['App\\EntityListener\\NotifyRegistrationConfirmation'] = new \App\EntityListener\NotifyRegistrationConfirmation(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
