<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_LegacySuccessListener_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.legacy_success_listener.main' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/LegacyLogoutHandlerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Logout/LogoutSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/AuthenticationHandler.php';

        return $container->privates['security.logout.listener.legacy_success_listener.main'] = new \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener(new \App\Security\AuthenticationHandler(($container->services['router'] ?? $container->getRouterService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));
    }
}
