<?php

namespace ContainerJkmjU67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadAvatarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\UploadAvatar' shared autowired service.
     *
     * @return \App\Services\UploadAvatar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/UploadAvatar.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        return $container->privates['App\\Services\\UploadAvatar'] = new \App\Services\UploadAvatar((\dirname(__DIR__, 4).'/assets/images/web/avatars'), ($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('en'))), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
